---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: sbeliakou/centos-7.4-x86_64-minimal

suites:
  - name: default
    driver:
      vm_hostname: jboss
      network:
      - ["private_network", {ip: "192.168.56.100"}]
    run_list:
      - recipe[day2::default]
      - recipe[day2::deploy]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
